IDE Basics
opalj/opal pull request #240
Opened 2024-11-15 15:35 UTC by Rkoer

- IDE infrastructure
- Basic IDE solver
- Example implementation of linear constant propagation
- Interaction capabilities
- Example implementation of a linear constant propagation on fields

2025-04-30 14:28 UTC, errt requested changes

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/lcp_on_fields/ArrayValue.java
> +    String variable();
Using (TAC) variable names could be fragile and is hard to understand by reading the source code. Maybe it would be better to identify variables by the line they are declared in.

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/fixtures/lcp_on_fields/ArrayNativeMethodExample.java
> +package org.opalj.fpcf.fixtures.lcp_on_fields;
Could it be sensible to move these into a subpackage of the fixtures.linear_constant_propagation package?

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/ide/IDEPropertiesTest.scala
> +class IDEPropertiesTest extends PropertiesTest {
This looks like it should be a trait / abstract class

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/ide/lcp_on_fields/LCPOnFieldsAnalysisScheduler.scala
> +object LCPOnFieldsAnalysisScheduler
I don't think you need this as a separate object, it should be possible to just put `new LCPOnFieldsAnalysisScheduler() with JavaIDEAnalysisSchedulerBase.RTACallGraph` at its single use. If it is needed, I caution agains naming it the same as its parent class, to avoid confusion.

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/AbstractRepeatablePropertyMatcher.scala
> +abstract class AbstractRepeatablePropertyMatcher extends AbstractPropertyMatcher {
This seems like a good idea. Can you apply it to the DirectCallMatcher as well (maybe in a separate PR)?

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/lcp_on_fields/LCPOnFieldsMatcher.scala
> +        val expectedVariableValues =
This and `expectedUnknownValues` are practically identical, so extracting a method with the "variableValues"/"unknownValues" as a parameter seems sensible. Could also potentially use this for the `expectedConstantValues`

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/lcp_on_fields/LCPOnFieldsMatcher.scala
> +        if (properties.exists {
This code of multiple wrapped exists/forall calls with partial functions (i.e., case matches) is hard to understand. Can it be simplified? If not, it should at least be documented what each step does.

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/lcp_on_fields/LCPOnFieldsMatcher.scala
> +        val expectedVariableValues =
Note that the `ArrayValueMatcher` and `StaticValuesMatcher` classes also use duplicated code to be extracted to a common base trait/class. Maybe an LCPOnFieldsMatcher trait to follow the file name.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaForwardICFG.scala
> + * [[org.opalj.tac.fpcf.analyses.ifds.JavaForwardICFG]] from IFDS.
Would it be possible to merge these implementations? It seems like a bad idea to maintain two very similar implementations when both IFDS and IDE could probably use the same

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/ICFG.scala
> +    def stringifyStatement(stmt: Statement, indent: String = "", short: Boolean = false): String
It seems weird to have this on the ICFG. Should it be on the statement (if needed at all)?

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaBaseICFG.scala
> +    override def stringifyStatement(javaStmt: JavaStatement, indent: String = "", short: Boolean = false): String = {
Is this even used with `short=false` or any indent anywhere? It seems that this method could be removed completely or moved to the `FlowRecordingIDEProblem`

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaBaseICFG.scala
> + * [[org.opalj.tac.fpcf.analyses.ifds.JavaICFG]] from IFDS.
See below, can this be merged with the IFDS variant to avoid duplication?

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +    /**
I don't understand the point of these traits

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +    trait RTACallGraph {
This should not be tied to RTA in particular, but allow users to pick a call graph algorithm of their choice.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +        super.uses.union(immutable.Set(
Use `++` or similar instead of `union`

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +    val callGraphKey: CallGraphKey
Is this really needed?

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +            callGraphKey
Also, is this really needed? CallGraphKeys are meant to make it easier to compute a call graph, but their use should not be mandated by analyses. Instead, having `Callers` (and/or `Callees`, depending on what the analysis actually uses) should suffice.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/linear_constant_propagation/problem/LinearConstantPropagationLattice.scala
> +        case (UnknownValue, y)                                  => y
This shadows the `y` parameter with a new `y`. Either use a new name or just use `_` here, since the `y` parameter is still available.
Also, use more descriptive names than x and y.

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/MeetLattice.scala
> +trait MeetLattice[Value <: IDEValue] {
Why is this a separate trait? Usually, we'd include things like the meet operator within the property class itself.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsValue.scala
> +    override def toString: String = s"StaticFieldValue($value)"
Is this necessary? Cases classes have a default toString

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/LinearConstantPropagationAnalysisSchedulerExtended.scala
> + * Extended linear constant propagation as IDE analysis.
What does `extended` mean here? Use a more descriptive name and improve the documentation.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/LCPOnFieldsAnalysisScheduler.scala
> +        super.uses.union(immutable.Set(
Use `++` or similar instead of `union`

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/LCPOnFieldsAnalysisScheduler.scala
> +        super.requiredProjectInformation ++ Seq(
If you only add one, avoid creating an additional Seq and use `:+` instead.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/LinearConstantPropagationAnalysisSchedulerExtended.scala
> +        super.uses.union(immutable.Set(
Use `:+` or similar instead of `union`

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/util/Logging.scala
> + * Logging extension for IDE.
Is this really needed? And is there anything IDE specific to it?

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysisProxy.scala
> + * callable. This proxy analysis reduces all analysis requests to the callable and then forward it to the actual IDE
`forwards them`?

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysisProxy.scala
> +        logInfo(s"proxying request to ${PropertyKey.name(propertyMetaInformation.key)} for $entity")
Is this necessary?

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/FlowRecordingIDEProblem.scala
> + * DOT files can either be viewed with a suitable local program or online e.g. at
I don't think an explanation on how to view DOT files is necessary here

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +        (otherEdgeFunction eq this) || otherEdgeFunction.isInstanceOf[IdentityEdgeFunction[Value]]
Don't do `isInstanceOf` (and `asInstanceOf`, below), but use pattern matching if possible.

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +    def equalTo(otherEdgeFunction: EdgeFunction[Value]): Boolean
Why isn't this just `equals`?

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +    def meetWith(otherEdgeFunction: EdgeFunction[Value]): EdgeFunction[Value]
Why isn't this just `meet`?

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/integration/IDERawProperty.scala
> + * @param key the property key (very likely taken from an [[IDERawPropertyMetaInformation]] instance)
`very likely` doesn't sound very reassuring.

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/integration/FlowRecordingAnalysisScheduler.scala
> + * DOT files can either be viewed with a suitable local program or online e.g. at
See below, explanation on DOT files probably not necessary

2025-04-30 14:28 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/ide/lcp_on_fields/LCPOnFieldsTests.scala
> +    describe("Execute the o.o.t.f.a.i.i.l.LCPOnFieldsAnalysis") {
Can probably live without the abbreviated packages

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +            .filter {
Consider using `.collect` instead of `.filter{ ... }.map{ ... }` as it is more efficient. Alternatively, it might be possible to integrate the `map` (or even the `filter`) into the `foldLeft`. Also consider using `fold` instead of `foldLeft` if possible.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +            .filter {
See above on replacing filter+map

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +            .filter {
See below on replacing filter+map

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +            case intRange: DefaultIntegerRangeValues#IntegerRange =>
Check if the type projection is necessary. OPAL is about to switch to Scala 3 which has dropped general type projection.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/linear_constant_propagation/problem/LinearConstantPropagationProblem.scala
> +            .filter { case (paramType, _) => paramType.isIntegerType }
Consider replacing filter+map with collect, which is more efficient.

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/linear_constant_propagation/problem/LinearConstantPropagationProblem.scala
> +        callee.parameterTypes
Consider placing a `.iterator` here to avoid repeatedly creating temporary collections

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +case class IdentityEdgeFunction[Value <: IDEValue]() extends EdgeFunction[Value] {
This should probably be a (case) object

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsEdgeFunctions.scala
> +            case AllTopEdgeFunction(_)    => this
If you don't need to match the parameters, you can replace cases like this with, e.g., `case _: AllTopEdgeFunction`

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsEdgeFunctions.scala
> +    override def toString: String = "NewObjectEdgeFunction()"
You can probably get rid of toString methods like this if you just make these objects `case object`s instead, which provide a default toString method

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                .filter { case (paramType, _) => paramType.isObjectType || paramType.isArrayType }
Consider replacing filter+map with collect, plus performing the whole operation on an iterator

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                .filter(_.isStatic)
Again, consider collect + iterator

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                    workingStmts = workingStmts.foldLeft(mutable.Set.empty[JavaStatement]) { (nextStmts, stmt) =>
Consider using fold over foldLeft if possible

2025-04-30 14:28 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +             immutable.Set.empty
It should be possible to get around all these `immutable.Set` by importing immutable.Set directly and importing mutable.Set with renaming, i.e., `import scala.collections.mutable.{Set => MutableSet}`

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +                    .filter { case (n, _) => icfg.isNormalExitStatement(n) }
Consider replacing filter+map with collect

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +        def areDependeesEmpty: Boolean = {
It would be more conventional to have a `hasDependees` method with inverted semantics

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +    private def performPhase1()(implicit s: State): Boolean = {
Phase1/Phase2 are very non-descriptive names. Try to come up with better ones and at the very least, document these methods properly to make the code understandable.

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +        logDebug("finished creation of properties and results")
Consider whether these log messages are really necessary

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +    private def processCallFlow(path: Path, f: JumpFunction, qs: collection.Set[Callable])(
This code is poorly documented and uses many nondescriptives names. What are things like `sp`, `n`, `rs`, `qs`, `d5`, `d5s`, `d3`, `sqs`, etc.

2025-04-30 14:28 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +class IDEAnalysis[Fact <: IDEFact, Value <: IDEValue, Statement, Callable <: Entity](
There are many complex methods in this class that should be properly documented, at least with a ScalaDoc on what they do.

2025-05-17 10:51 UTC, Rkoer commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/lcp_on_fields/ArrayValue.java
> +    String variable();
I guess we could add this, but there are tests (not the ones for LCPoF but esp. the ones for LCP) are more detailed and also check values that are not explicitly declared in the code.

2025-05-17 10:58 UTC, Rkoer commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/fixtures/lcp_on_fields/ArrayNativeMethodExample.java
> +package org.opalj.fpcf.fixtures.lcp_on_fields;
That sounds logical. However, at the moment there are two separate test classes, one for LCP and one for LCPoF. When moving the fixtures inside the linear_constant_propagation package then the tests for LCP do pick up the fixtures for LCPoF too. I guess we would need to specify each test fixture for LCP manually instead of providing the package. Is there an alternative solution to this?

2025-05-17 11:37 UTC, Rkoer commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/AbstractRepeatablePropertyMatcher.scala
> +abstract class AbstractRepeatablePropertyMatcher extends AbstractPropertyMatcher {
Sure, see PR#274

2025-05-17 15:26 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/lcp_on_fields/ArrayValue.java
> +    String variable();
Can we identify them by program counter or line number then? Program counters are at least guaranteed to be stable since we use a fixed compiler. Line numbers are a little more fragile as one might make non-semantic changes to the source files, but they are easier to understand from the source code.

2025-05-17 15:27 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/fixtures/lcp_on_fields/ArrayNativeMethodExample.java
> +package org.opalj.fpcf.fixtures.lcp_on_fields;
How about one fixture directory with two subdirectories, for LCP and LCPoF?

2025-05-24 11:52 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaForwardICFG.scala
> + * [[org.opalj.tac.fpcf.analyses.ifds.JavaForwardICFG]] from IFDS.
The IDE variant relies on separate call-site and return-site nodes which do not exist in the IFDS variant. It also deals with call statements differently (e.g. the IDE solver does not allow for call statements without call targets while the IFDS solver treats such call statments as normal statements). Merging the implementations seems possible to me but requires changes to the IFDS solver and potentially breaks existing IFDS problem specifications.

2025-05-24 12:00 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaBaseICFG.scala
> +    override def stringifyStatement(javaStmt: JavaStatement, indent: String = "", short: Boolean = false): String = {
I used the stringification of statements in the solver for debugging (in general there are many `logDebug` statments i used to understand and debug the solver). I guess in one of the following comments you mentioned to remove some of the log statements. Do you want me to remove the logging (or maybe just the debug messages) from the solver entirely? In this case i would remove the `stringifyStatement` also instead of refactoring it.

2025-05-24 12:03 UTC, Rkoer commented on OPAL/ide/src/main/scala/org/opalj/ide/util/Logging.scala
> + * Logging extension for IDE.
It is not in particular IDE specific. I used debug and trace messages to debug the solver. OPAL did only offer warn, info and debug messages. Differentiating between debug and trace allowed me to log more information only if debug information did not suffice to find bugs.

2025-05-24 17:13 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +    /**
It allows to build analysis schedulers by using mixins (e.g. `with JavaIDEAnalysisSchedulerBase.ForwardICFG`and `with JavaIDEAnalysisSchedulerBase.RTACallGraph`) instead of implementing the corresponding methods fully by hand in the analysis scheduler.

2025-05-24 17:17 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +    trait RTACallGraph {
One has to write a separate trait per call graph algorithm to use this scheme of configuring the analysis scheduler. It is not required to use JavaIDEAnalysisSchedulerBase. One can as well implement the methods that these traits provide by hand in the analysis scheduler. I just considered it a convenient way to build IDE analysis schedulers and abstracting over the detailed implementation of how to configure the call graph key (and the ICFG).

2025-05-24 17:35 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/integration/JavaIDEAnalysisSchedulerBase.scala
> +            callGraphKey
Ah, now i get what you mean. I guess dependencies to Callers is already there. I removed the `callGraphKey` property as well as the `RTACallGraphKey` trait.

2025-05-31 12:10 UTC, Rkoer commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/MeetLattice.scala
> +trait MeetLattice[Value <: IDEValue] {
I decided to model this separately and closer to the IDE problem definition because it is the lattice for IDE values. The meet-implementations i have seen in the code of other OPAL analyses are rather about meeting the resulting analysis properties. For IDE this would include the IDE fact in addition to the IDE value. But i think i could move it into the property definition if you want me to.

2025-06-02 13:42 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/util/Logging.scala
> + * Logging extension for IDE.
In this case, maybe expand the general logging facilities with trace messages instead of adding this only in the IDE subproject?

2025-06-02 13:44 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaBaseICFG.scala
> +    override def stringifyStatement(javaStmt: JavaStatement, indent: String = "", short: Boolean = false): String = {
In general, yes, I'd suggest to remove most logging. Messages (of the appropriate logging levels) should primarily be used to notify users of things that might affect their analysis, not to provide information into the analysis process itself.

2025-06-02 13:45 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaForwardICFG.scala
> + * [[org.opalj.tac.fpcf.analyses.ifds.JavaForwardICFG]] from IFDS.
There are not many existing IFDS problems, so merging now would probably be a good idea before more client analyses exist and implementations diverge even more.

2025-06-02 13:57 UTC, errt requested changes

2025-06-02 13:57 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/properties/ide/IDEPropertyMatcherMixin.scala
> +trait IDEPropertyMatcherMixin extends AbstractPropertyMatcher {
Remove `Mixin` from the name

2025-06-02 13:57 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
> +     * The PC of this variable in the TAC
PCs are not a property of the TAC, but of the bytecode. Do not confuse them with TAC indices.

2025-06-02 13:57 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +                case IdentityEdgeFunction() => true
Better: `case _: IdentityEdgeFuction`

But given this case class has no fields, shouldn't it be a `case object` anyway so the equality boils down to `otherEdgeFunction eq this`?

2025-06-09 09:58 UTC, Rkoer commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +case class IdentityEdgeFunction[Value <: IDEValue]() extends EdgeFunction[Value] {
I am sorry, but i don't know how this can be done in the presence of generics. Should i use Value=IDEValue and cast the edge function everywhere where the specific type is expected?

2025-06-09 18:35 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsEdgeFunctions.scala
> +    override def toString: String = "NewObjectEdgeFunction()"
It seems like case objects do not override an existing toString implementation of the superclass

2025-06-10 08:46 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +case class IdentityEdgeFunction[Value <: IDEValue]() extends EdgeFunction[Value] {
I think you'd need to make `Value` covariant (i.e., `[+Value <: IDEValue]`) and change the functions taking an `EdgeFunction[Value]` take an `[B >: Value] EdgeFunction[B]` to make it work. In which case I believe it would be `IdentityEdgeFunction extends EdgeFunction[Nothing]` (or `Null`)

2025-06-10 08:51 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsEdgeFunctions.scala
> +    override def toString: String = "NewObjectEdgeFunction()"
Oh, I see. Yes, you can't have a `case object` inheriting from a `case class`

2025-06-12 14:04 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
I think it should be possible to merge this into the fold as well

2025-06-12 14:04 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
>       */
Thanks for updating the documentation, but is it correct now? The code suggests that the values here might not be bytecode PCs but maybe TAC indices.

2025-06-12 14:04 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +            .foldLeft(UnknownValue: LinearConstantPropagationValue)(lattice.meet)
Why is it a `foldLeft` here, but a general `fold` in the other two cases?

2025-06-12 14:04 UTC, errt commented on OPAL/ide/src/main/resources/reference.conf
>  org.opalj {
Is this config file still required? It is empty now.

2025-06-15 14:05 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
You mean performing the pattern match inside the fold-callback?

2025-06-15 14:12 UTC, Rkoer commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
>       */
I had the same thought, but it originates from `CFG.foreachSuccessor`. Maybe i misunderstood the corr. code?

2025-06-15 15:04 UTC, Rkoer commented on OPAL/ide/src/main/scala/org/opalj/ide/problem/EdgeFunction.scala
> +case class IdentityEdgeFunction[Value <: IDEValue]() extends EdgeFunction[Value] {
Ah ok, i tried to integrate this.

2025-06-15 15:08 UTC, Rkoer commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +class IDEAnalysis[Fact <: IDEFact, Value <: IDEValue, Statement, Callable <: Entity](
The most of this (e.g. phase 1, phase 2, sp, n, rs, qs, d5, ...) are named as done in the original algorithm. This helps to associate the paths from the Scala Code with the parts in the Pseudocode of the foundation paper. I'll think about, how this can be made clearer, e.g. with additional documentation.

2025-06-16 07:22 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
Yes, it seems that should be possible

2025-06-16 07:24 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
>       */
CFG is a generic class agnostic of the underlying code representation. CFGs of bytecode will have PCs, but CFGs of TAC will have TAC indices.

2025-06-16 07:27 UTC, errt commented on OPAL/ide/src/main/scala/org/opalj/ide/solver/IDEAnalysis.scala
> +class IDEAnalysis[Fact <: IDEFact, Value <: IDEValue, Statement, Callable <: Entity](
I figured this by now. You are right that keeping close to the original algorithm is a good idea, but documentation would be really helpful here. Both a link to the paper itself and some code documentation that explains what different parts, methods, variables, etc. are for.

2025-06-21 11:14 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
I applied this to one occurrence in LCPOnFieldsProblem (see commit 57452f63). IMO this makes the code more complicated. Mainly, because the fold operates on a different data type than the collect (this is what previously was done by the separate map operator). So this requires the fold to operate on type Object instead of the specific types and requires a cast at the end. As fold requires associativeness (compared to foldLeft) and Object is used as type it is also required to catch more cases in the fold (only differing in the tuple order). Please let me know whether i should apply this to the other occurrences too or rather stay with collect and fold combination.

2025-06-21 11:32 UTC, Rkoer commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
>       */
In this case i would rename the whole parameter in the JavaStatement class from "pc" to "tacIndex" as this implementation is for TAC. Same for the validation annotations. Is this a suitable solution in your opinion?

2025-07-08 14:30 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                        .map(icfg.getNextStatements)
Why did you pull this out? It seems the former version was probably more efficient. General rule of thumb: Try not to chain any collection transforming methods (map, filter, fold, etc.) since they create intermediate collections. If it can't be avoided, at least perform them on an iterator to avoid the intermediate collections.

2025-07-08 14:30 UTC, errt commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/linear_constant_propagation/lcp/ConstantValue.java
>       */
Yes, that seems a reasonable solution. PCs tend to be more stable though (we're using a fixed compiler so they will never change, while TAC indices could change if we changed the implementation).

2025-07-08 14:30 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
It probably only works properly with `foldLeft` there due to the different types. Alternatively, if you want to keep the collect+fold, do it on an iterator. Otherwise, the collect will create a new Set which is both kind of costly (for sets especially, since the uniqueness constraint has to be checked for every entry) and takes up memory, but this is not necessary since we immediately process the values anyway and don't need them stored and also we don't need the set property (i.e., unique elements) since the fold is idempotent for identical elements anyway.

2025-07-13 11:18 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                        .map(icfg.getNextStatements)
I did it to replace the foldLeft by a fold. But I can revert this if you want me to. For now i adjusted it to use the iterator solution.

2025-07-13 12:43 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LinearConstantPropagationProblemExtended.scala
> +                case (f: AbstractArrayFact, ArrayValue(initValue, values))
Ok, I understand. I modified the code to use the iterator solution.

2025-07-14 10:39 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/instances/lcp_on_fields/problem/LCPOnFieldsProblem.scala
> +                        .map(icfg.getNextStatements)
I don't see why the foldLeft would be bad. But you can also do it using an iterator. Just avoid the intermediate collections where possible.

2025-08-03 21:16 UTC, Rkoer commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/ide/solver/JavaForwardICFG.scala
> + * [[org.opalj.tac.fpcf.analyses.ifds.JavaForwardICFG]] from IFDS.
I've put my suggestion for this in PR#300

2025-08-04 10:23 UTC, errt approved these changes
LGTM now

2025-08-04 10:33 UTC, merged