Improve handling of `java/lang/System` entry points in CG generation
opalj/opal pull request #241
Opened 2024-11-29 15:50 UTC by johannesduesing

This PR resulted from issues discussed in #230, in particular the fact that calls to `System.out.println` are not found by OPAL with multiple CG algorithms when the `RTJar` is loaded (either interfaces-only or fully). The reasons for this are depending on the CG algorithm and configuration, but boil down to:
* RTA cannot find an instantiation of `PrintWriter` (the type of `System.out`) when `RTJar` is loaded as interfaces only - it is simple never instantiated
* Somewhere between JDK9 and JDK11, they switched from using `System.initializeSystemClass` (which we model as an initial entrypoint in the config) to using `System.initPhase1`, `System.initPhase2` and `System.initPhase3` - all of which are called from native code and currently **not** configered to be initial entry points. This is another reason why RTA - even when the RTJar is loaded fully - does not find calls to `println`.
* Propagation-Based algorithms never found a write to `System.out` that initializes the field (even when `RTJar` is loaded fully) - the reason for this is that the fields are set in native code

*Side-Note*: This was never a problem when the `RTJar` was **not** loaded, because `CallGraphAnalysis.unknownLibraryCall` caught any calls to virtual methods (like `println` in this scenario).

**Changes in this PR**
This PR introduces some changes to tackle the problems mentioned above. This includes:
* Declare `initPhase1`, `initPhase2` and `initPhase3` of type `java/lang/System` to be initial entry points in the config - see [the OpenJDK implementation](https://github.com/openjdk/jdk/blob/4da7c3548436ffffb009828891df0d13d47370e3/src/java.base/share/classes/java/lang/System.java#L1753) for details on this.
* Always consider `java/lang/Thread`, `java/lang/ClassLoader`, `java/io/PrintStream` and `java/io/InputStream` to be instantiated via config
* Improve propagation-based cg algorithms - they now always assume that `System.out`, `System.in` and `System.err` are instantiated with their declared types by adding them to the respective `typeSetEntity` - furthermore, we now always assume that the configured instantiated types are available for the `ExternalWorld` type set entity.

With these changes CHA, RTA and all Propagation-Based CG algorithms will now find calls to `System.out.println`, regardless of whether the `RTJar` is loaded at all, as interfaces only, or fully.

**What's still to do**

- [ ] Find more types that should always be considered instantiated - if possible define a method for identifying those types and add them to the config
- [ ] Analyze why the CFA-Algorithms both do not find calls to `println` and fix the issue
- [ ] There is still an issue with library fields if the library is loaded as interfaces only. We will likely have no writes to those fields, as the library method bodys are not loaded, therefore propagation-based algorithms will never consider the fields instantiated. They are also not considered `ExternalWorld` because their definition is available, therefore they cannot be treated differently compared to "normal" project fields. Decide on whether those cases deserve special handling or not - we might just have to live with that fact.

2024-11-29 16:22 UTC, errt commented
Thank you for the extensive investigation and the PR. I fully agree with the additions to the config and with adding instantiated types to `ExternalWorld`.

I'm a little wary however with `System.{in,out,err}` special handling for the propagation-based CGs. Could this not lead to scenarios where RTA is less sound than the propagation-based CGs because RTA doesn't have this modeling? Also, different to changes to the config, this can never be overridden for an analysis of a Java System that might behave differently (Android maybe?). Is there another way this could be achieved, e.g., modeling the native methods that set the fields?
If we decide to keep your approach, I'd suggest to make it more general by not hardcoding the `System` class into it. It could also be made configurable via the config files which fields should be initialized.

For the last future work item: That is  a fair point. I think we could deal with it like you suggested, though maybe rather than setting them to the field type, they could access the `ExternalWorld` like they would without loading the interfaces? That would also solve the issue above with `System.{in,out,err}`, right?

2024-12-02 16:17 UTC, johannesduesing commented
I think you make a good point. I restructured parts of this PR so that now:
* There is an `InitialInstantiatedFieldsKey` and corresponding `InstantiatedFieldsFinder` to detect fields that shall always be considered instantiated
* Very similar to the `InstantiatedTypesFinder` it has a configurable aspect so that users can specify fields to be considered instantiated. By default the field type will be considered only, but specific types and subtype-trees can be specified in the config.
* The `SoundLibraryInstantiatedFieldsFinder` (implemented but not used by default) would consider all library fields to be instantiated with their declared type if libraries are interfaces only - this could address the last future work item

I think this might be a good solution to the problem - analyses for android can just remove the three lines from the configuration, and they also don't introduce any overhead of libraries are not loaded at all. 

Regarding your suggestion for associating library fields with `ExternalWorld` if libraries are interfaces only: I had that exact solution implemented earlier, but i does not really scale to *any* library besides the `RTJar` - users would have to manually specify the types of their library fields every time they use a new / different library.

What do you think of this idea, does that work for you?

2024-12-02 16:20 UTC, johannesduesing commented
Oh i forgot to mention: The `rta.InstantiatedTypesAnalysis` and `xta.InstantiatedTypesAnalysis` now both use the `InitialInstantiatedFieldsKey` for their respective initialization, thus (hopefully) fixing the issue that RTA could sometimes be less sound than XTA.

2024-12-03 09:16 UTC, errt commented
This solution sounds reasonable. Thank you for your work!

About the `ExternalWorld`: true for _manual_ specification of types. A suitable `InitialInstantiatedTypesFinder` would do this automatically however.

2024-12-03 13:08 UTC, johannesduesing commented
My latest commit adds support for the initial intantiated fields to CFA-1-0 and CFA-1-1. For the latter i had to create dummy allocation sites as the fields are defined in native code - i don't know if that is the way to go, but it seems to work as expected.

So regarding the library fields and the `ExternalWorld` we now have two options:
* Leave it as it currently is. We have the `SoundLibraryInstantiatedFieldsFinder` that can detect those fields and mark them as instantiated. All CG algorithms respect the initial instantiated fields in their respective initialization phases.
* Explicitly associate library fields (if libraries are interfaces only) with the `ExternalWorld` set entity. This will really only work with Propagation-Based algorithms, since RTA and CFA-1-* do not work on set entities (at least i did not see them using `ExternalWorld` anywhere). It would require implementing a suitable `InitialInstantiatedTypesFinder` that would maybe rely on the `InitialInstatiatedFieldsFinder`. The downside would be that we would have to adapt the CG algorithm(s) when it comes to finding instantiated fields in order to encode this specific case.

Is there any specific reason you think we should use the second option? I'm currently thinking the first one should be less overhead, but maybe i'm missing something .. 🤓

2024-12-03 15:49 UTC, errt commented
You can have a look at `ConfiguredMethodsPointsToAnalysis`, it needs to do the same for allocation sites in native or otherwise unavailable methods.

The main reason for choosing the second option would be to have fewer necessary modifications. For RTA, it would work immediately, as RTA just uses instantiated types and thus the proper InitialInstantiatedTypesFinder will automatically make it work. For the propagation-based ones it would be just the single line that adds the InitialInstantiatedTypes to the ExternalWorld that we probably want to have anyway. The InstantiatedFieldsFinders would not be necessary. For the points-to-based algorithms, it should be similar: one handling for instantiated types (that we probably need anyway if we don't yet have it) instead of that and the additional one for the fields.
So my question is, where do you see the benefit of the first option? The one that I see is that it could be more specific, in adding types only to individual fields instead of a (potentially large) set of initially instantiated types being available through all (matching - but that could still be many, e.g., `Object` fields) fields.

2024-12-03 15:50 UTC, errt requested changes

2024-12-03 15:50 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/InitialInstantiatedFieldsKey.scala
> +package org.opalj.br.analyses.cg
Please fix package declaration to OPAL's standard of one package per line

2024-12-03 16:04 UTC, johannesduesing commented
There are two points why i think the first option may be the better one:
* Like you said, it's more specific and should keep loss of precision to a minimum for Propagation-Based algorithms and CFA - if we load large libraries as interfaces, the `ExternalWorld` could become very large.
* The second option does not work for fields being set in native code if the library contents are actually loaded. If we go with the second option, at least for `System.{out, err, in}` the callgraphs will not capture `println` if the `RTJar` is actually loaded - it works if libraries are interfaces only.

So in my mind, if we want to capture fields being set in native code - and i'm open to discussing whether or not we want that - then we need an `InitialInstatiatedFieldsFinder`, otherwise it won't work in the case that libraries are actually fully loaded.

That being said, if you want me to implement the second option i'll do that - justed wanted to point that out 😄

2024-12-03 16:08 UTC, errt commented
Shouldn't the second point already be addressed by the configured native methods analyses? I thought it was.

2024-12-05 14:18 UTC, johannesduesing commented
After discussion, we will proceed as follows:
* Remove InitialInstantiatedFieldsFinder
* Use configured native methods to model effects of `setOut0` & others
* Add more instantiated types, see [here](https://github.com/openjdk/jdk/blob/308357cba706478598ef231887e0584eaae839e0/src/hotspot/share/runtime/threads.cpp#L295) 
* Also model effects of `initPhase1` and others so calls can be detected if RTJar is interface only

2024-12-10 10:20 UTC, johannesduesing commented
After some further inspection i think this is not going to be as easy as we thought it would. I found that:
* `setOut0` and others are already modeled with their field-setting effects in the config - with the new entrypoints in the config as well, RTA out of the Box finds calls to `System.out.println` **if the RTJar is loaded**
* I was confused that Propagation-Based Algorithms did not find those calls with the RTJar loaded. I found that the `PropagationBasedCallGraphKeys` use the `rta.ConfiguredNativeMethodsInstantiatedTypesAnalysisScheduler` (see [here](https://github.com/opalj/opal/blob/f8a8fc179bd99697c1e08076a1fd9c8340cca824/OPAL/tac/src/main/scala/org/opalj/tac/cg/PropagationBasedCallGraphKeys.scala#L64)). This does not make sense to me, this analysis was specifically written for RTA and attaches all configured instantiated types to the Project entity - as far as my understanding of any of the propagation-based CG algorithms goes, this is conceptually not compatible with XTA & co, which use typeSetEntities to attach types to.
* When loading the `RTJar` as interfaces only, i am facing another issue: The EntryPointsFinder does not consider methods without bodies. This means that even though i carefully configured the effects of `System.initPhase1` with its instantiations and invocations, it is simply never considered by the CG framework, which expects entrypoints to have a body.

If my assessment is correct, i think the following steps would be sensible to take next:
* Write a new `ConfiguredNativeMethodsInstantiatedTypesAnalysis` for XTA & co. I started doing this, but found that because the configuration can state that "This fields is assigned the value of the first parameter" (which is what we have for `setOut0`), it needs to be a lot more complex than the one for RTA, as it would need continuations and dependencies on its caller property - maybe it would be sensible to integrate it into the existing TypePropagationAnalysis for XTA? (It would be structurally very similar and use a lot of the same constructs)
* Consider entrypoints even if they are empty, provided that native method configurations exist for them - unfortunately the correpsonding configuration (plus deserialization utilities) are in the TAC project while entrypoints are in BR, meaning i can't access them directly. I removed the emptiness check for debugging purposes and it did not work as expected out of the box, so this would likely require more debugging

What do you think of this? Is this the right way to go?

2024-12-10 10:35 UTC, errt commented
You are right, they are configured to use the RTA class there, which doesn't seem to make much sense. Not sure why that is, I thought there already was a variant for XTA, but apparently, there isn't. So yes, it looks like we need to add that.

For the other issue, it looks like entry points should always be considered, even without a body. I don't think it is necessary that they have configuration attached, they could still just exist without any callees. They should probably _exist_ (so you don't get spurious methods in the CG that are configured as entry point for a different setup than you analyze), but bodies should not be necessary. I wonder why removing the emptiness check didn't just work, so yes, that should be looked into.

Thank you for your investigation!

2025-09-12 18:06 UTC, johannesduesing commented
/it:test

2025-09-12 18:16 UTC, johannesduesing commented
In my opinion, this PR is done now. My local experiments showed that OPAL can now correctly detect calls to `System.out.println` for CHA, RTA, XTA, 1-0-CFA and 1-1-CFA when the JRE is not loaded, loaded as interfaces only or fully loaded. Many things changed throughout the development, so here's the most important points:
* The `EntryPointsFinder` now works on `DeclaredMethod`s instead of `Method`s. Consequently, it now propagates configured entry point methods even if the do not exist in the project - they are then represented as `VirtualDeclaredMethods`.
* All call graph related analyses- especially those related to reading configured behavior - can now deal with the fact that entry points may be virtual
* `DefinitionSites` now use `DeclaredMethod`s instead of `Method`s. This enables us to propagate virtual definition sites for configured points-to behavior in methods that are not actually part of the project. The points-to framework has been adapted to deal with this change.
* The XTA framework got its own `ConfiguredNativeMethodsInstantiatedTypesAnalysis` - previously it used the same as RTA, which did work in the XTA context.

Let me know what you think of those changes - i'll wait for the IT tests to complete and see if the changes broke any test cases.

2025-09-15 09:16 UTC, errt requested changes

2025-09-15 09:16 UTC, errt commented on OPAL/br/src/main/resources/reference.conf
> +            "java/lang/ClassLoader",
Can you document why these are instantiated?
Also, if Thread is considered instantiated, we may want to consider whether to add ThreadGroup as well.

2025-09-15 09:16 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +        }.map(declaredMethods.apply)
It would probably be more efficient to move the apply into the the collect, avoiding an additional intermediate collection. Additionally or alternatively, it could be more efficient to perform the collect on an iterator.

2025-09-15 09:16 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +        super.collectEntryPoints(project) ++ eps.map(declaredMethods.apply)
As above, performing the apply immediately instead of with a `map` would remove an intermediate collection. The code above could also probably be improved (along the lines of `val eps = project.allMethodsWithBody.iterator.filter(isEntryPoint)`

2025-09-15 09:16 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +                            entryPoints = entryPoints ++ Set(virtualEntry)
The intermediate Set here is probably not necessary

2025-09-15 09:16 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +            project.allProjectClassFiles.flatMap(_.methodsWithBody).map(declaredMethods.apply)
Can probably pull the apply into the flatMap

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/resources/reference.conf
> +          {
Please add some (short) documentation on why these methods are included and what they do.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/TypeIterator.scala
> +                        DefinitionSite(declaredMethods(method), defPC),
Remove this apply, use `definedMethod` from line 990 (and probably remove `method` from line 991 completely.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/TypeIterator.scala
> +                        DefinitionSite(declaredMethods(method), defPC),
Same as above, this is already available from line 1231, which also means the DeclaredMethodsKey should not be necessary here

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        initialize(ExternalWorld, initialInstantiatedTypes)
Not sure why String and Class are initialized for the project, but these other types for the external world.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +        val readAccessEOptP = methodOpt.map(m => propertyStore(m, MethodFieldReadAccessInformation.key)).orNull
Shouldn't we do this with `Option`s instead of `null`s?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +        val typeSetEntity = selectTypeSetEntity(callContext.method)
Maybe extract callContext.method to a variable since it is used multiple times.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +            // we soundly assume that the call might be virtual, and we need to add "this".
Remove the comma

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +        val returnValueIsUsed = if (!state.methodHasBody) true
Could think about writing this as `= !state.methodHasBody || {`, but not sure if that is better.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationState.scala
> +        callContext.method.hasSingleDefinedMethod && callContext.method.definedMethod.body.isDefined
Should we deal with `MultipleDefinedMethods`?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationState.scala
> +        if (_readAccessDependee != null && _readAccessDependee.isRefinable) Some(_readAccessDependee) else None
Should probably document the potential nullness of these fields

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> +            s"init: ${simplifiedName(method)} (initial types: {${initialTypes.map(simplifiedName).mkString(
Check if formatting can be improved here

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/escape/AbstractEscapeAnalysis.scala
> +        // TODO: Handle VirtualDeclaredMethods
What about this TODO? Should this `targetMethod` also just be a `DeclaredMethod`?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ConfiguredMethodsPointsToAnalysis.scala
> +                    // Configured Calls are made at PC=0, so we need to expand the context accordingly
But should they?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // TODO remove dependency to classes in pointsto package
What about this TODO?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +        processMethodInternal(callContext)
I think we could just call `processMethodWithoutBody` and have the implementation there.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +) extends ReachableMethodAnalysis {
Should the RTA variant of this analysis also be a `ReachableMethodAnalysis`?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +        if (!nativeMethodData.contains(callContext.method)) {
Maybe extract callContext.method to a variable since it is used multiple times.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // Taken from rta TypePropagationAnalysis
This doesn't make sense. There's no TypePropagationAnalysis for RTA.
Also, instead of duplicating the code, is there a way to reuse it?

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    private def processStaticConfigurations(implicit
Document this and the following method, they are not trivial.

2025-09-15 09:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +            .filter(_.pointsTo.isDefined)
In the RTA variant of this analysis, there is a case that is not present in this analysis and that I think can not be added with this filter being present: https://github.com/opalj/opal/blob/fc0b1f52b3f8812450e73b4af742e8bdaf11d93e/OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/rta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala#L98-L108
This code considers the return type of a method that was not configured to be instantiated if we don't have a method body (i.e., native methods). I believe this was done particularly for methods used in reflection implementing functionality such as Class.get[Declared](Method|Field)[s].
Is this really not necessary for the propagation-based analyses?

2025-09-15 09:19 UTC, errt commented
As the failed it:test shows, this PR needs re-generation of the `FPCFAnalysesIntegrationTest` reference files. This seems to be because of changes to the entities for the escape analysis? Given the scope of this PR, a deeper look into the files might be sensible to ensure that nothing else was broken.

2025-09-15 15:08 UTC, johannesduesing commented on OPAL/br/src/main/resources/reference.conf
> +            "java/lang/ClassLoader",
I now consider all non-static classes for which we have configured entry points to be instantiated and added documentation. I checked with the OpenJDK implementation, those classes are indeed instantiated by the JVM.

2025-09-15 15:09 UTC, johannesduesing commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +        }.map(declaredMethods.apply)
Moved apply into the collect and used an iterator - seems to be consensus that this is the best way in terms of performance.

2025-09-15 15:09 UTC, johannesduesing commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +        super.collectEntryPoints(project) ++ eps.map(declaredMethods.apply)
Same as above 👍

2025-09-15 15:09 UTC, johannesduesing commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +                            entryPoints = entryPoints ++ Set(virtualEntry)
Removed unecessary set

2025-09-15 15:10 UTC, johannesduesing commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +            project.allProjectClassFiles.flatMap(_.methodsWithBody).map(declaredMethods.apply)
Did that

2025-09-15 15:10 UTC, johannesduesing commented on OPAL/tac/src/main/resources/reference.conf
> +          {
Added documentation on why methods are included and brief description on each individual points-to assignment.

2025-09-15 15:12 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        initialize(ExternalWorld, initialInstantiatedTypes)
I think i inherited this code, it says in the comment above that initializing `String` and `Class` may be required for *"Some cooperative analyses originally meant for RTA"* - i do not know if this is still the case, without the `initialize(p, [...])` the code still works on my testbench...

2025-09-15 15:12 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +        val readAccessEOptP = methodOpt.map(m => propertyStore(m, MethodFieldReadAccessInformation.key)).orNull
Did that

2025-09-15 15:13 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +            // we soundly assume that the call might be virtual, and we need to add "this".
Which one? 😅  If you are referring to the one after "virtual" - the IntelliJ grammar checker tells me to keep it whenver i remove that.

2025-09-15 15:14 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +        val returnValueIsUsed = if (!state.methodHasBody) true
I honestly think it is more readable the way it is now

2025-09-15 15:14 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        initialize(ExternalWorld, initialInstantiatedTypes)
The question was not whether we want String and Class here - we do. The question is why are different initially instantiated types here in different sets. It seems that either they should all be in `p` or all in `ExternalWorld`.

2025-09-15 15:14 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationState.scala
> +        if (_readAccessDependee != null && _readAccessDependee.isRefinable) Some(_readAccessDependee) else None
Should not be necessary, i made these types an `Option` now

2025-09-15 15:16 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationState.scala
> +        callContext.method.hasSingleDefinedMethod && callContext.method.definedMethod.body.isDefined
Very good question - the entire `TypePropagationAnalysis` currently does not really support that. It requires either one or no actual implementations. If you think that's necessary i will have a look, but it will require some larger refactoring work.

2025-09-15 15:16 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> +            s"init: ${simplifiedName(method)} (initial types: {${initialTypes.map(simplifiedName).mkString(
Tried something different, is that better?

2025-09-15 15:16 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationAnalysis.scala
> +            // we soundly assume that the call might be virtual, and we need to add "this".
Yes. I'm not sure the grammar checker is correct there, since that makes it a new, unrelated sentence as far as I understand. Probably remove the "we" too and it won't complain, though.

2025-09-15 15:17 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationState.scala
> +        callContext.method.hasSingleDefinedMethod && callContext.method.definedMethod.body.isDefined
Let's leave it the way it is then

2025-09-15 15:19 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ConfiguredMethodsPointsToAnalysis.scala
> +                    // Configured Calls are made at PC=0, so we need to expand the context accordingly
Are you asking whether configured calls should be made at PC=0? If so, i am unsure... We have multiple different analyses that handle the integration of configured values into the call graph. For example for the points-to configuration, the corresponding analysis "makes up" (negative) PC values to assign points-to information to. The analysis responsible for configured method invocations decides to use PC=0 for all calls - since the two of them are not really "communicating" it would be hard to make them agree on one specific "virtual PC layout".

2025-09-15 15:22 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ConfiguredMethodsPointsToAnalysis.scala
> +                    // Configured Calls are made at PC=0, so we need to expand the context accordingly
Yes, that was my question. I see the issue. Does this cause any potential problems (especially, if there are multiple invocations configured, could we end up with a situation where the points-to sets end up containing the wrong values)? If not, let's keep it.

2025-09-16 12:11 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // TODO remove dependency to classes in pointsto package
I'd like to just remove the `TODO` comment. We do not depend on anything from the actual `pointsto` package, only the `tac.fpcf.analyses.PointsToRelation` class which represents the configured data. This is necessary to derive instantiated types information from - i do not see how that would be a problem.

2025-09-16 12:13 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // TODO remove dependency to classes in pointsto package
I tend to agree. Though we might consider renaming the class since what it models is rather an assignment than specifically points-to information.

2025-09-16 12:45 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +) extends ReachableMethodAnalysis {
Makes sense to me, i changed it to also use the trait 👍

2025-09-16 12:46 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // Taken from rta TypePropagationAnalysis
I think that was a typo, i meant to say i took it from the xta analysis - in any case, i moved that piece of code to the appropirate package object where i think it makes the most sense.

2025-09-16 12:53 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +    // TODO remove dependency to classes in pointsto package
I renamed `PointsToRelation` to `EntityAssignment`, as i think that's essentially what the class is - hope that works for you.

2025-09-17 08:23 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/escape/AbstractEscapeAnalysis.scala
> +        // TODO: Handle VirtualDeclaredMethods
Made the Escape Analysis framework used DeclaredMethods alltogether

2025-09-17 08:23 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        initialize(ExternalWorld, initialInstantiatedTypes)
As we figured out together yesterday, i removed the initialization of types for the Project `p` as it should no longer be required.

2025-09-17 08:31 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +                    // If the virtual formal parameter is null (we are in a virtual method) or the origin is unknown,
We might have to have a look into the VirtualFormalParameters(Key) and check whether it should not, like the DeclaredMethodsKey, support creating new VirtualFormalParameters for VirtualDeclaredMethods when queried. The way it is now, it creates them for all DeclaredMethods that are available when the VirtualFormalParametersKey is first computed, which is not deterministic since the DeclaredMethods can be extended any time by querying for a VirtualDeclaredMethod

2025-09-17 09:00 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +            .filter(_.pointsTo.isDefined)
After our discussion yesterday i added this feature to XTA as well

2025-09-17 09:35 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +                    // If the virtual formal parameter is null (we are in a virtual method) or the origin is unknown,
I do agree, i thought the same thing when looking into the issue. However, i do not think that should be part of this PR, as i would expect the impact to be relatively big. If that's okay with you, i'll leave this as it is and create an issue for updating the VirtualFormalParameter computations in a separate PR.

2025-09-17 09:45 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +                    // If the virtual formal parameter is null (we are in a virtual method) or the origin is unknown,
Sure, just let's not forget about it.

2025-09-17 09:51 UTC, johannesduesing commented
/it:test

2025-09-17 09:56 UTC, johannesduesing commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ConfiguredNativeMethodsInstantiatedTypesAnalysis.scala
> +                    // If the virtual formal parameter is null (we are in a virtual method) or the origin is unknown,
I created #316 to document this

2025-09-17 12:39 UTC, johannesduesing commented
@errt I updated most expected values for the IT test, i unfortunately do not have the resources at hand to generate the `ExtensiveAnalysesTest-OPAL-MultiJar-SNAPSHOT-01-04-2018-dependencies.txt.gz` file. I looked through the changes of two archives in depth and found that they really only differed in the `toString` representation of methods. If you want me to i can do some further investigation, but i am confident that there are no unintended behavioral changes.

Can you regenerate the missing expected value befor i rerun the IT tests?

2025-09-17 14:35 UTC, errt approved these changes
Looks complete now

2025-09-17 14:35 UTC, johannesduesing commented
/it:test

2025-09-18 06:58 UTC, merged