Use Twirl instead of scalate
opalj/opal pull request #35
Opened 2021-07-08 16:51 UTC by TorunR

* Refactor Template accordingly
* Invokes the twirl template using reflection. This is ugly but it
  works.

2021-07-09 08:26 UTC, errt requested changes

2021-07-09 08:26 UTC, errt commented on build.sbt
> +    libraryDependencies += Dependencies.scalaCompiler(scalaVersion.value),
Wouldn't it make sense to define this in the Dependencies file like the values for, e.g., bi and br?

2021-07-09 08:26 UTC, errt commented on project/SiteGeneration.scala
> +
Formatting: Too many blank lines

2021-07-09 08:26 UTC, errt commented on project/SiteGeneration.scala
> +                    sourceDirectory: File,
Formatting: Wrong indentation

2021-07-09 08:26 UTC, errt commented on src/site/defaultTemplate.scala.html
> +@(title:String,content:String,toc:Traversable[(String,String)],useBanner:Boolean)
Formatting: Spaces after commas would make this more readable if that is allowed

2021-07-09 10:22 UTC, errt commented
The code looks good to me now, but did you check the output? The HTML seems severely broken for the table of contents. E.g., now quotation marks are generated around anchor urls, headings are generated as
`<a href=/null.html>Text</a><br>` instead of `<br><b>Further Tutorials</b><br>`
and there is lots of additional whitespace.
The commented out script has also reappeared in the output.

2021-07-09 10:24 UTC, TorunR commented
I did check only an intermediate Version. I'll have to recheck

2021-07-09 13:59 UTC, errt approved these changes
LGTM now, thanks!

2021-07-09 14:24 UTC, errt requested changes
Nope, urls of TOC still without quotation marks...

2021-07-13 13:03 UTC, errt approved these changes

2021-07-13 15:02 UTC, merged