Added Nested Classes to ClassFileBuilderTest
opalj/opal pull request #54
Opened 2022-01-25 18:40 UTC by JuliusNmn

Test runs fine

2022-01-26 11:37 UTC, errt reviewed
LGTM, but please address comment.

2022-01-26 11:37 UTC, errt commented on OPAL/ba/src/test/scala/org/opalj/ba/ClassFileBuilderTest.scala
> +            version = UShortPair(0, 49),
Is this the proper Java version? Also, I suggest we move this upwards so features introduced later (i.e., with a higher version number here) are later in this file.

2022-02-06 18:51 UTC, JuliusNmn commented
The initial pull request did not test the NestHost attribute. This has been added.

2022-02-14 08:33 UTC, errt requested changes
I think the class file versions are still wrong. Also, the CI failed in formatting, so please run `sbt scalariformFormat`.

2022-02-28 15:26 UTC, errt requested changes
LGTM, just please reorder the code so that features are handled in order of their addition to the JVM (i.e., by class file version). Once that is done, I'll approve this PR.

2022-03-09 10:22 UTC, JuliusNmn reviewed
classes have been ordered by class file version

2022-03-09 10:23 UTC, errt submitted a review, later dismissed

2022-03-09 14:31 UTC, errt approved these changes

2022-03-09 14:32 UTC, merged